language: python

cache: pip

sudo: false

env:
    - TOX_ENV='py3-flake8'
    - TOX_ENV='py27-django1.6-drf{3.0,3.1,3.2}'  # DRF >= 3.3 dropped support for Django 1.6
    - TOX_ENV='py27-django1.7-drf{3.0,3.1,3.2,3.3}'
    - TOX_ENV='py27-django1.8-drf{3.0,3.1,3.2,3.3}'
    - TOX_ENV='py27-django1.9-drf{3.1,3.2,3.3}'  # DRF supports Django 1.9 only since 3.1
    - TOX_ENV='py33-django{1.6,1.7}-drf{3.2}'  # Django >= 1.8 dropped support for py < 3.4
    - TOX_ENV='py34-django1.6-drf{3.0,3.1,3.2}'  # DRF >= 3.3 dropped support for Django 1.6
    - TOX_ENV='py34-django1.7-drf{3.0,3.1,3.2,3.3}'
    - TOX_ENV='py34-django1.8-drf{3.0,3.1,3.2,3.3}'
    - TOX_ENV='py34-django1.9-drf{3.1,3.2,3.3}'  # DRF supports Django 1.9 only since 3.1
    - TOX_ENV='py35-django{1.8,1.9}-drf{3.3}'  # Django supports py 3.5 only since 1.8
    - TOX_ENV='py3-slow-tests'

matrix:
  fast_finish: true

services:
  - docker

before_install:
  - docker pull geometalab/postgis-with-translit
  - docker run -d -p "127.0.0.1:54321:5432" -e POSTGRES_DB='postgres' --name pg_tests geometalab/postgis-with-translit
  - docker ps -a
  - sleep 10

install:
  - pip install detox

script:
    - detox -e $TOX_ENV
